# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('pc_mail_address', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('mobile_mail_address', models.EmailField(max_length=100)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('control_level', models.IntegerField(blank=True, null=True)),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_finish_time', models.TimeField(blank=True, null=True)),
                ('mail_detination', models.IntegerField(blank=True, null=True)),
                ('work_day', models.IntegerField(blank=True, null=True)),
                ('t01_author', models.IntegerField(blank=True, null=True)),
                ('t01_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('t01_updater', models.IntegerField(blank=True, null=True)),
                ('t01_update_time', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
