# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enzemi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalMaster',
            fields=[
                ('goals_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'goal_master',
            },
        ),
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('holiday', models.DateTimeField(blank=True, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'holiday_master',
            },
        ),
        migrations.CreateModel(
            name='MajorClassificationMaster',
            fields=[
                ('major_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_classification', models.CharField(blank=True, max_length=100)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'major_classification_master',
            },
        ),
        migrations.CreateModel(
            name='MorningCommentMaster',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'morning_comment_master',
            },
        ),
        migrations.CreateModel(
            name='MorningTaskMaster',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('importance', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('major_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzemi.MajorClassificationMaster')),
            ],
            options={
                'managed': True,
                'db_table': 'morning_task_master',
            },
        ),
        migrations.CreateModel(
            name='NightCommentMaster',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'night_comment_master',
            },
        ),
        migrations.CreateModel(
            name='NightTaskMaster',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('importance', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('situation', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('major_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzemi.MajorClassificationMaster')),
            ],
            options={
                'managed': True,
                'db_table': 'nighy_task_master',
            },
        ),
        migrations.CreateModel(
            name='ReviewMaster',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('this_month', models.IntegerField(blank=True, default=0, null=True)),
                ('review_month', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'review_master',
            },
        ),
        migrations.CreateModel(
            name='SmallClassificationMaster',
            fields=[
                ('small_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('small_classification', models.CharField(blank=True, max_length=100)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('major_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzemi.MajorClassificationMaster')),
            ],
            options={
                'managed': True,
                'db_table': 'small_classification_master',
            },
        ),
        migrations.CreateModel(
            name='TeamInter',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'team_inter',
            },
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'team_list',
            },
        ),
        migrations.AddField(
            model_name='nighttaskmaster',
            name='small_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzemi.SmallClassificationMaster'),
        ),
        migrations.AddField(
            model_name='morningtaskmaster',
            name='small_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzemi.SmallClassificationMaster'),
        ),
    ]
