# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-17 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enzemi', '0005_auto_20170317_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeelist',
            old_name='mobile_mail_address',
            new_name='mobile_address',
        ),
        migrations.RenameField(
            model_name='employeelist',
            old_name='pc_mail_address',
            new_name='pc_address',
        ),
    ]
